name: Build and Push to Aliyun ACR

on:
  push:
    branches: [ "main" ]  # 每次 push 到 main 分支时自动执行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: crpi-gmih3z2dkjr1lre8.cn-hangzhou.personal.cr.aliyuncs.com/spenny/ubuntu:latest
